####################################
### Virtual Machine
####################################
vagrant:
    vm:
       box: centos65_x64
       box_url: https://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.5-x86_64-v20140504.box
       ip: 192.168.11.11
       hostname: dev-libra

    ssh:
       port: 1111

    network:
       forwarded_port:
          1:
               host: '9999'
               guest: '22'
          2:
               host: '80'
               guest: '80'
          3:
               host: '8080'
               guest: '8080'
          4:
               host: '3306'
               guest: '3306'
               
       auto_correct:
            status:  true
         
